defmodule FlyrankCapstoneSocialStudio.Content do
  @moduledoc """
  The Content context.
  """

  import Ecto.Query, warn: false
  alias FlyrankCapstoneSocialStudio.Repo

  alias FlyrankCapstoneSocialStudio.Content.Post
  alias FlyrankCapstoneSocialStudio.Content.Variant
  alias FlyrankCapstoneSocialStudio.Content.ConstraintProfile

  # Existing Post CRUD functions generated by Phoenix ...
  def list_posts, do: Repo.all(Post)
  def get_post!(id), do: Repo.get!(Post, id)

  def create_post(attrs \\ %{}) do
    %Post{}
    |> Post.changeset(attrs)
    |> Repo.insert()
  end

  def update_post(%Post{} = post, attrs) do
    post
    |> Post.changeset(attrs)
    |> Repo.update()
  end

  def delete_post(%Post{} = post) do
    Repo.delete(post)
  end

  def change_post(%Post{} = post, attrs \\ %{}) do
    Post.changeset(post, attrs)
  end

  # Variant CRUD & Generation functions ...

  def list_variants, do: Repo.all(Variant)
  def get_variant!(id), do: Repo.get!(Variant, id)

  def get_post_variants(post_id) do
    from(v in Variant, where: v.post_id == ^post_id)
    |> Repo.all()
  end

  def create_variant(attrs \\ %{}) do
    %Variant{}
    |> Variant.changeset(attrs)
    |> Repo.insert()
  end

  def update_variant(%Variant{} = variant, attrs) do
    variant
    |> Variant.changeset(attrs)
    |> Repo.update()
  end

  @doc """
  Ingests a blog post and generates initial platform variants for all requested platforms.
  """
  def ingest_and_generate(post_attrs, platforms \\ ["telegram", "mock_x", "mock_linkedin"]) do
    Repo.transaction(fn ->
      case create_post(post_attrs) do
        {:ok, post} ->
          variants =
            Enum.map(platforms, fn platform ->
              case generate_variant_for_platform(post, platform) do
                {:ok, variant} -> variant
                {:error, changeset} -> Repo.rollback(changeset)
              end
            end)

          {post, variants}

        {:error, changeset} ->
          Repo.rollback(changeset)
      end
    end)
  end

  @doc """
  Generates a variant content draft tailored to a platform's constraint profile.
  """
  def generate_variant_for_platform(%Post{} = post, platform) do
    profile = ConstraintProfile.get(platform)

    if profile do
      generated_text = draft_text_for_platform(post.content, profile)

      create_variant(%{
        post_id: post.id,
        platform: platform,
        content: generated_text,
        status: "draft"
      })
    else
      {:error, :unsupported_platform}
    end
  end

  # Basic deterministic template transformer based on platform limits
  defp draft_text_for_platform(content, profile) do
    # Trim content to fit platform limit while preserving hashtag allocation space
    max_text_len = profile.max_length - 20
    trimmed_content = String.slice(content, 0, max_text_len)

    hashtags =
      case profile.max_hashtags do
        1 -> " #tech"
        2 -> " #tech #news"
        _ -> " #tech #news #update"
      end

    trimmed_content <> hashtags
  end

  @doc """
  Approves a variant after re-validating platform constraint rules.
  """
  def approve_variant(%Variant{} = variant) do
    variant
    |> Variant.changeset(%{status: "approved"})
    |> Repo.update()
  end

  @doc """
  Rejects a variant with an optional rejection reason.
  """
  def reject_variant(%Variant{} = variant, reason \\ "Content rejected by reviewer") do
    variant
    |> Variant.changeset(%{status: "rejected", rejection_reason: reason})
    |> Repo.update()
  end
end
